apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploader4misp-instance
  namespace: default
  labels:
    app: uploader4misp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: standard   # Uncomment and set for your cluster
